### ISSUE TITLE
Flag Read

### ISSUE THREAD

**Issue by C15C01337** [naryal2580/Bypass-Me#1]
flag{831e4488f707a1a3077f7dd51d583d17}

**Comment by naryal2580** [comment]
Please provide the payload too, that is making the flag read. Thanks.

**Comment by C15C01337** [comment]
payload

"filename=../flag/flag.txt"

**Comment by naryal2580** [comment]
Awesome!! Congratulations for solving the challenge. Good luck, for another round.
